export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Layout } from './Layout';
export { default as PaintingCard } from './PaintingCard';
export { default as PaintingGrid } from './PaintingGrid';
export { default as PaintingModal } from './PaintingModal';
export { default as FilterBar } from './FilterBar';
export { default as Gallery } from './Gallery';
export { default as About } from './About';
export { default as Homepage } from './Homepage';
export { default as ShoppingCart } from './ShoppingCart';
export { default as PerformanceDebugger } from './PerformanceDebugger';
export { default as CartItem } from './CartItem';
export { default as AddToCartButton } from './AddToCartButton';
export { default as CheckoutForm } from './CheckoutForm';
export { default as CheckoutPage } from './CheckoutPage';
export { default as PaymentForm } from './PaymentForm';
export { default as OrderConfirmation } from './OrderConfirmation';
export { default as ContactPage } from './ContactPage';
export { default as ContactFormSubmit } from './ContactFormSubmit';
export { default as ContactSuccess } from './ContactSuccess';
export { default as TestimonialCard } from './TestimonialCard';
export { default as TestimonialCarousel } from './TestimonialCarousel';
export { default as TestimonialSection } from './TestimonialSection';

// Admin Components
export { AdminLogin } from './AdminLogin';
export { AdminDashboard } from './AdminDashboard';
export { AdminLayout } from './AdminLayout';
export { AdminApp } from './AdminApp';
export { ProtectedRoute } from './ProtectedRoute';
export { PaintingManager } from './PaintingManager';
export { PaintingForm } from './PaintingForm';
export { ImageUploader } from './ImageUploader';
export { OrderManager } from './OrderManager';
export { OrderDetail } from './OrderDetail';
export { TestimonialManager } from './TestimonialManager';
export { TestimonialForm } from './TestimonialForm';
export { ContactManager } from './ContactManager';
export { OptimizedImage, useResponsiveImageUrls } from './OptimizedImage';
export { ErrorBoundary, useErrorHandler } from './ErrorBoundary';